package NADA_GUI;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nurshabah
 */
public class MenuPetugas extends javax.swing.JFrame {
    public Login form1;
    public Connection conn;
    public Statement cn;
    public void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/studio","root","");
            cn=conn.createStatement();
        } catch(ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal....");
            System.out.println(e.getMessage());
        }
    }
    public void bersih(){
        idDaftarTxt.setText("");
        namaDaftarTxt.setText("");
        no_telpDaftarTxt.setText("");
        alamatDaftarTxt.setText("");
        HapusDaftar.setEnabled(false);
        EditDaftar.setEnabled(false);
        SimpanDaftar.setEnabled(true);
    }
    public void bersihsewa(){
        no_sewaTxt.setText("");
        idSewaTxt.setText("");
        namaSewaTxt.setText("");
        no_telpSewaTxt.setText("");
        alamatSewaTxt.setText("");
        nostudioCmb.setSelectedItem("--PILIH--");
        paketCmb.setSelectedItem("--PILIH--");
        hargaTxt.setText("");
    }

    /**
     * Creates new form TesPetugas
     */
    public MenuPetugas() {
        initComponents();
        setLocationRelativeTo(this);
        tanggal();
        tampildata();
        tampildatasewa();
        AutoNumberSewa();
        AutoNumber();
        HapusDaftar.setEnabled(false);
        EditDaftar.setEnabled(false);
        SimpanDaftar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idDaftarTxt = new javax.swing.JTextField();
        namaDaftarTxt = new javax.swing.JTextField();
        no_telpDaftarTxt = new javax.swing.JTextField();
        alamatDaftarTxt = new javax.swing.JTextField();
        EditDaftar = new javax.swing.JButton();
        HapusDaftar = new javax.swing.JButton();
        SimpanDaftar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        no_sewaTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tanggalTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        idSewaTxt = new javax.swing.JTextField();
        namaSewaTxt = new javax.swing.JTextField();
        no_telpSewaTxt = new javax.swing.JTextField();
        alamatSewaTxt = new javax.swing.JTextField();
        hargaTxt = new javax.swing.JTextField();
        simpanSewaBtn = new javax.swing.JButton();
        nostudioCmb = new javax.swing.JComboBox();
        paketCmb = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmember1 = new javax.swing.JTable();
        pencariantxt = new javax.swing.JTextField();
        pencarianbtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsewa1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        Bantuan = new javax.swing.JMenuItem();
        AboutProgramMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NADA Music Studio");

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 260));

        jLabel1.setText("ID Member");

        jLabel2.setText("Nama");

        jLabel3.setText("No Telepon");

        jLabel4.setText("Alamat");

        idDaftarTxt.setEditable(false);
        idDaftarTxt.setBackground(new java.awt.Color(204, 204, 204));
        idDaftarTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idDaftarTxtFocusLost(evt);
            }
        });
        idDaftarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDaftarTxtActionPerformed(evt);
            }
        });

        namaDaftarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaDaftarTxtKeyTyped(evt);
            }
        });

        no_telpDaftarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                no_telpDaftarTxtKeyTyped(evt);
            }
        });

        alamatDaftarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alamatDaftarTxtKeyTyped(evt);
            }
        });

        EditDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit-button-png-hi.png"))); // NOI18N
        EditDaftar.setToolTipText("");
        EditDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDaftarActionPerformed(evt);
            }
        });

        HapusDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete-button-png-hi.png"))); // NOI18N
        HapusDaftar.setToolTipText("");
        HapusDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusDaftarActionPerformed(evt);
            }
        });

        SimpanDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-button-png-hi.png"))); // NOI18N
        SimpanDaftar.setToolTipText("");
        SimpanDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanDaftarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alamatDaftarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(no_telpDaftarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaDaftarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idDaftarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HapusDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SimpanDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idDaftarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaDaftarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(no_telpDaftarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatDaftarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel3))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SimpanDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HapusDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Daftar Member", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("No Sewa");

        no_sewaTxt.setEditable(false);
        no_sewaTxt.setBackground(new java.awt.Color(204, 204, 204));
        no_sewaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                no_sewaTxtFocusLost(evt);
            }
        });
        no_sewaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_sewaTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Tanggal");

        tanggalTxt.setEditable(false);
        tanggalTxt.setBackground(new java.awt.Color(204, 204, 204));
        tanggalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalTxtActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Data Sewa"));

        jLabel8.setText("ID Member");

        jLabel9.setText("Nama Member");

        jLabel10.setText("No Telepon");

        jLabel11.setText("Alamat");

        jLabel12.setText("No Studio");

        jLabel13.setText("Paket Sewa");

        jLabel14.setText("Harga Sewa");

        idSewaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idSewaTxtFocusLost(evt);
            }
        });
        idSewaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSewaTxtActionPerformed(evt);
            }
        });
        idSewaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idSewaTxtKeyTyped(evt);
            }
        });

        namaSewaTxt.setEditable(false);
        namaSewaTxt.setBackground(new java.awt.Color(204, 204, 204));
        namaSewaTxt.setToolTipText("");
        namaSewaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaSewaTxtActionPerformed(evt);
            }
        });

        no_telpSewaTxt.setEditable(false);
        no_telpSewaTxt.setBackground(new java.awt.Color(204, 204, 204));

        alamatSewaTxt.setEditable(false);
        alamatSewaTxt.setBackground(new java.awt.Color(204, 204, 204));

        hargaTxt.setEditable(false);
        hargaTxt.setBackground(new java.awt.Color(204, 204, 204));

        simpanSewaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-button-png-hi.png"))); // NOI18N
        simpanSewaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanSewaBtnActionPerformed(evt);
            }
        });

        nostudioCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ruang 1", "Ruang 2", "Ruang 3", "Ruang 4" }));

        paketCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Jam", "2 Jam", "3 Jam", "4 Jam", "5 Jam" }));
        paketCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no_telpSewaTxt)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alamatSewaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idSewaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaSewaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(108, 108, 108)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paketCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nostudioCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simpanSewaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(idSewaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(namaSewaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(no_telpSewaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nostudioCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(paketCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(hargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(alamatSewaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(simpanSewaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(no_sewaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(no_sewaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tanggalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sewa Studio", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        tblmember1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmember1.setToolTipText("");
        tblmember1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblmember1.setName(""); // NOI18N
        tblmember1.getTableHeader().setResizingAllowed(false);
        tblmember1.getTableHeader().setReorderingAllowed(false);
        tblmember1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblmember1FocusGained(evt);
            }
        });
        tblmember1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmember1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblmember1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblmember1);

        pencariantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencariantxtActionPerformed(evt);
            }
        });

        pencarianbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pencarianbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cari.png"))); // NOI18N
        pencarianbtn.setText("Cari");
        pencarianbtn.setToolTipText("Mencari data apapun di dalam database");
        pencarianbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pencariantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pencarianbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pencariantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarianbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );

        jTabbedPane1.addTab("Data Member", jPanel3);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        tblsewa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblsewa1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Data Sewa", jPanel5);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button-logout.png"))); // NOI18N
        jButton4.setToolTipText("Logout akun");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(153, 153, 153));
        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 0, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("NADA Music Studio");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setPreferredSize(new java.awt.Dimension(164, 24));

        jMenu4.setText("Bantuan");

        Bantuan.setText("Bantuan");
        Bantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantuanActionPerformed(evt);
            }
        });
        jMenu4.add(Bantuan);

        AboutProgramMenu.setText("Tentang Aplikasi");
        AboutProgramMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutProgramMenuActionPerformed(evt);
            }
        });
        jMenu4.add(AboutProgramMenu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(338, 338, 338)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tanggal(){
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        tanggalTxt.setText(s.format(ys));
    }
    private void idDaftarTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idDaftarTxtFocusLost
        if(idDaftarTxt.getText()==""){
            namaDaftarTxt.setText("");
            no_telpDaftarTxt.setText("");
            alamatDaftarTxt.setText("");
            
        }
        else{
            try{
                koneksi();
                String sql="select nama_member,no_telepon,alamat from member where id_member='"+idDaftarTxt.getText()+"'";
                Statement stat = conn.createStatement();
                ResultSet rs=stat.executeQuery(sql);
                while(rs.next()){
                    namaDaftarTxt.setText(rs.getString("nama_member"));
                    no_telpDaftarTxt.setText(rs.getString("no_telepon"));
                    alamatDaftarTxt.setText(rs.getString("alamat"));
                    HapusDaftar.setEnabled(true);
                    EditDaftar.setEnabled(true);
                    SimpanDaftar.setEnabled(false);

                }
            }catch(Exception e){
                e.printStackTrace();

            }
        }
    }//GEN-LAST:event_idDaftarTxtFocusLost

    private void EditDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDaftarActionPerformed
        String ObjButtons[] = {"Ya","Tidak"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah data yang anda isi sudah benar?","Peringatan",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
            try{

                koneksi();
                String sql="Update member set nama_member='"+namaDaftarTxt.getText()+"',"+"no_telepon='"+no_telpDaftarTxt.getText()+"',"+"alamat='"+alamatDaftarTxt.getText()+"'"+"where id_member='"+idDaftarTxt.getText()+"'";
                cn.executeUpdate(sql);
                conn.close();
                bersih();
                AutoNumber();
                JOptionPane.showMessageDialog(null,"Data berhasil di rubah");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal...");
                System.out.println(e.getMessage());
            }
            idDaftarTxt.setEnabled(true);
        }
    }//GEN-LAST:event_EditDaftarActionPerformed

    private void HapusDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusDaftarActionPerformed
        String ObjButtons[] = {"Ya","Tidak"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah anda yakin hapus data ini?","Peringatan",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
            try{

                koneksi();
                String sql="delete from member where id_member='"+idDaftarTxt.getText()+"'";
                cn.executeUpdate(sql);
                conn.close();
                bersih();
                AutoNumber();
                JOptionPane.showMessageDialog(null,"Data berhasil di hapus");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal...");
                System.out.println(e.getMessage());

            }
            idDaftarTxt.setEnabled(true);
        }
    }//GEN-LAST:event_HapusDaftarActionPerformed

    private void SimpanDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanDaftarActionPerformed
        String ObjButtons[] = {"Ya","Tidak"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah data yang anda isi sudah benar?","Peringatan",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
            try{

                koneksi();
                String sql="Insert into member values('"+idDaftarTxt.getText()+"','"+namaDaftarTxt.getText()+"','"+no_telpDaftarTxt.getText()+"','"+alamatDaftarTxt.getText()+"')";
                cn.executeUpdate(sql);
                conn.close();
                bersih();
                AutoNumber();

                JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Proses penyimpanan gagal/koneksi gagal..");
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null,"No id : "+idDaftarTxt.getText()+" sudah ada...!!!");
                System.out.println(e.getMessage());
                bersih();
            }
        }
    }//GEN-LAST:event_SimpanDaftarActionPerformed

    private void no_sewaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_no_sewaTxtFocusLost
        if(idSewaTxt.getText()==""){
            idSewaTxt.setText("");
            namaSewaTxt.setText("");
            no_telpSewaTxt.setText("");
            alamatSewaTxt.setText("");
        }
        else{
            try{
                koneksi();
                String sql="select id_member,nama_penyewa,no_telepon,alamat,ruang_studio,paket_sewa,harga_sewa,tanggal from sewa where no_sewa='"+no_sewaTxt.getText()+"'";
                Statement stat = conn.createStatement();
                ResultSet rs=stat.executeQuery(sql);
                while(rs.next()){
                    idSewaTxt.setText(rs.getString("id_member"));
                    namaSewaTxt.setText(rs.getString("nama_penyewa"));
                    no_telpSewaTxt.setText(rs.getString("no_telepon"));
                    alamatSewaTxt.setText(rs.getString("alamat"));
                    nostudioCmb.setSelectedItem(rs.getString("ruang_studio"));
                    paketCmb.setSelectedItem(rs.getString("paket_sewa"));
                    hargaTxt.setText(rs.getString("harga_sewa"));
                    tanggalTxt.setText(rs.getString("tanggal"));

                }
            }catch(Exception e){
                e.printStackTrace();

            }
        }
    }//GEN-LAST:event_no_sewaTxtFocusLost

    private void no_sewaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_sewaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_sewaTxtActionPerformed

    private void tanggalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalTxtActionPerformed

    private void idSewaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idSewaTxtFocusLost
        if(idSewaTxt.getText()==""){
            namaSewaTxt.setText("");
            no_telpSewaTxt.setText("");
            alamatSewaTxt.setText("");
        }
        else{
            try{
                koneksi();
                String sql="select nama_member,no_telepon,alamat from member where id_member='"+idSewaTxt.getText()+"'";
                Statement stat = conn.createStatement();
                ResultSet rs=stat.executeQuery(sql);
                while(rs.next()){
                    namaSewaTxt.setText(rs.getString("nama_member"));
                    no_telpSewaTxt.setText(rs.getString("no_telepon"));
                    alamatSewaTxt.setText(rs.getString("alamat"));

                }
            }catch(Exception e){
                e.printStackTrace();

            }
        }
    }//GEN-LAST:event_idSewaTxtFocusLost

    private void idSewaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSewaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSewaTxtActionPerformed

    private void namaSewaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaSewaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaSewaTxtActionPerformed

    private void simpanSewaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanSewaBtnActionPerformed
        String ObjButtons[] = {"Ya","Tidak"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah data yang anda isi sudah benar?","Peringatan",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){

            try{
                koneksi();
                String sql="Insert into sewa values('"+no_sewaTxt.getText()+"','"+idSewaTxt.getText()+"','"+namaSewaTxt.getText()+"','"+no_telpSewaTxt.getText()+"','"+alamatSewaTxt.getText()+"','"+nostudioCmb.getSelectedItem()+"','"+paketCmb.getSelectedItem()+"','"+hargaTxt.getText()+"','"+tanggalTxt.getText()+"')";
                cn.executeUpdate(sql);
                conn.close();
                bersihsewa();
                AutoNumberSewa();
                JOptionPane.showMessageDialog(null,"Data berhasil disimpan");
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal");
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null,"ID Member : "+idSewaTxt.getText()+" belum terdaftar");
                System.out.println(e.getMessage());
                bersihsewa();
            }

        }// TODO add your handling code here:
    }//GEN-LAST:event_simpanSewaBtnActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        tampildata();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        tampildatasewa();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        tampildata();
        tampildatasewa();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        form1 = new Login();
        form1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void paketCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketCmbActionPerformed
        if(paketCmb.getSelectedItem()=="1 Jam"){
            hargaTxt.setText("25000");
        }
        else if(paketCmb.getSelectedItem()=="2 Jam"){
            hargaTxt.setText("50000");
        }
        else if(paketCmb.getSelectedItem()=="3 Jam"){
            hargaTxt.setText("75000");
        }
        else if(paketCmb.getSelectedItem()=="4 Jam"){
            hargaTxt.setText("100000");
        }
        else if(paketCmb.getSelectedItem()=="5 Jam"){
            hargaTxt.setText("125000");
        }
    }//GEN-LAST:event_paketCmbActionPerformed

    private void pencariantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencariantxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencariantxtActionPerformed

    private void pencarianbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianbtnActionPerformed
DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Member");
        tbl.addColumn("Nama Member");
        tbl.addColumn("No Telepon");
        tbl.addColumn("Alamat");
       
       
        try{
            koneksi();
            String sql="Select id_member, nama_member, no_telepon, alamat from member where nama_member like'%"+pencariantxt.getText()+"%'"+"or id_member like'%"+pencariantxt.getText()+"%'"+"or alamat like'%"+pencariantxt.getText()+"%'"+"or no_telepon like'%"+pencariantxt.getText()+"%'";
           Statement stat = conn.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while (rs.next())
            {
                tbl.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4)
               
            });
            }
            tblmember1.setModel(tbl);
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null,"Ada Kesalahan"); 
        }
    }//GEN-LAST:event_pencarianbtnActionPerformed

    private void AboutProgramMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutProgramMenuActionPerformed
        new AboutProgram().setVisible(true);
    }//GEN-LAST:event_AboutProgramMenuActionPerformed

    private void idDaftarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDaftarTxtActionPerformed

    }//GEN-LAST:event_idDaftarTxtActionPerformed

    private void tblmember1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmember1MouseClicked
        int table=tblmember1.getSelectedRow();
        String a =tblmember1.getValueAt(table, 0).toString();
        
        try{
            koneksi();
            String sql="select*from member where id_member='"+a+"'";
            Statement stat = conn.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                idDaftarTxt.setText(rs.getString("id_member"));
                namaDaftarTxt.setText(rs.getString("nama_member"));
                no_telpDaftarTxt.setText(rs.getString("no_telepon"));
                alamatDaftarTxt.setText(rs.getString("alamat"));
                HapusDaftar.setEnabled(true);
                EditDaftar.setEnabled(true);
                SimpanDaftar.setEnabled(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblmember1MouseClicked

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void tblmember1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmember1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblmember1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new help().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblmember1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblmember1FocusGained
        HapusDaftar.setEnabled(true);
    }//GEN-LAST:event_tblmember1FocusGained

    private void no_telpDaftarTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_telpDaftarTxtKeyTyped
        if ( no_telpDaftarTxt.getText().length() == 12 ) {
        evt.consume();
        }
    }//GEN-LAST:event_no_telpDaftarTxtKeyTyped

    private void namaDaftarTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaDaftarTxtKeyTyped
        if ( namaDaftarTxt.getText().length() == 20 ) {
        evt.consume();
        }
    }//GEN-LAST:event_namaDaftarTxtKeyTyped

    private void alamatDaftarTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamatDaftarTxtKeyTyped
        if ( alamatDaftarTxt.getText().length() == 50 ) {
        evt.consume();
        }
    }//GEN-LAST:event_alamatDaftarTxtKeyTyped

    private void idSewaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idSewaTxtKeyTyped
        if ( idSewaTxt.getText().length() == 5 ) {
        evt.consume();
        }
    }//GEN-LAST:event_idSewaTxtKeyTyped

    private void BantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantuanActionPerformed
        new help().setVisible(true);
    }//GEN-LAST:event_BantuanActionPerformed
    public void tampildata(){
        DefaultTableModel tblmember = new DefaultTableModel();
        tblmember.addColumn("ID Member");
        tblmember.addColumn("Nama");
        tblmember.addColumn("No Telepon");
        tblmember.addColumn("Alamat");
        
        try{
            koneksi();
            String sql="Select*from member order by id_member asc";
            ResultSet rs=cn.executeQuery(sql);
            while(rs.next())
            {
                tblmember.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4)
            });
            }
            tblmember1.setModel(tblmember);

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ada kesalahan");
        }

    }
public void tampildatasewa(){
        DefaultTableModel tblsewa = new DefaultTableModel();
        tblsewa.addColumn("No Sewa");
        tblsewa.addColumn("ID Member");
        tblsewa.addColumn("Nama Penyewa");
        tblsewa.addColumn("No Telepon");
        tblsewa.addColumn("Alamat");
        tblsewa.addColumn("Ruang Studio");
        tblsewa.addColumn("Paket Sewa");
        tblsewa.addColumn("Harga Sewa");
        tblsewa.addColumn("Tanggal");
        
        try{
            koneksi();
            String sql="Select*from sewa order by no_sewa asc";
            ResultSet rs=cn.executeQuery(sql);
            while(rs.next())
            {
                tblsewa.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8),
                rs.getString(9)
            });
            }
            tblsewa1.setModel(tblsewa);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ada kesalahan");
        }
    }
public void AutoNumberSewa() {
        try {
            String sql = "SELECT MAX(right(no_sewa,2)) AS no_sewa FROM sewa";
            koneksi();
            ResultSet rs=cn.executeQuery(sql);
                while (rs.next()){
                    if(rs.first()== false){
                      no_sewaTxt.setText("NS0001");
                    }
                    else{
                        rs.last();
                        int auto_id = rs.getInt(1)+1;
                        String no = String.valueOf(auto_id);
                        int noLong = no.length();
                            for(int a = 0; a<4-noLong; a++){
                                no = "0" + no;
                            }
                            no_sewaTxt.setText("NS"+ no);
                    }
                }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error: \n" + e.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
public void AutoNumber() {
        try {
            String sql = "SELECT MAX(right(id_member,2)) AS id_member FROM member";
            koneksi();
            ResultSet rs=cn.executeQuery(sql);
                while (rs.next()){
                    if(rs.first()== false){
                      idDaftarTxt.setText("M0001");
                    }
                    else{
                        rs.last();
                        int auto_id = rs.getInt(1)+1;
                        String no = String.valueOf(auto_id);
                        int noLong = no.length();
                            for(int a = 0; a<4-noLong; a++){
                                no = "0" + no;
                            }
                            idDaftarTxt.setText("M"+ no);
                    }
                }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error: \n" + e.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutProgramMenu;
    private javax.swing.JMenuItem Bantuan;
    private javax.swing.JButton EditDaftar;
    private javax.swing.JButton HapusDaftar;
    private javax.swing.JButton SimpanDaftar;
    private javax.swing.JTextField alamatDaftarTxt;
    private javax.swing.JTextField alamatSewaTxt;
    private javax.swing.JTextField hargaTxt;
    private javax.swing.JTextField idDaftarTxt;
    private javax.swing.JTextField idSewaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField namaDaftarTxt;
    private javax.swing.JTextField namaSewaTxt;
    private javax.swing.JTextField no_sewaTxt;
    private javax.swing.JTextField no_telpDaftarTxt;
    private javax.swing.JTextField no_telpSewaTxt;
    private javax.swing.JComboBox nostudioCmb;
    private javax.swing.JComboBox paketCmb;
    private javax.swing.JButton pencarianbtn;
    private javax.swing.JTextField pencariantxt;
    private javax.swing.JButton simpanSewaBtn;
    private javax.swing.JTextField tanggalTxt;
    private static volatile javax.swing.JTable tblmember1;
    private javax.swing.JTable tblsewa1;
    // End of variables declaration//GEN-END:variables

    String bersih(String m001) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
